name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi_app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/fastapi_app:${{ github.sha  }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Generate Docker Compose file
      run: |
        echo "
        version: '3'
        services:
          fastapi:
            image: ${{ secrets.DOCKER_USERNAME}}/fastapi_app:${{ github.sha }}
            ports:
              - '8888:8888'
        " > ansible/docker-compose.yml

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_private_key
        chmod 600 ssh_private_key

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
      run: |
        ansible-playbook -i ansible/inventory.ini ansible/deploy.yml --private-key ssh_private_key -u votanak
